/**
 * Login locators — {{APP_NAME}}.
 *
 * SEED FILE: generated by `/qa-agent:setup`. Login is the one module the
 * skeleton ships pre-wired, because `shared/auth.setup.ts` cannot authenticate
 * without it. The selectors below are the common form-attribute fallback; the
 * login screen of most apps predates a `data-testid` standard, which is the
 * documented exception to the testid-first rule (CLAUDE.md §4).
 *
 * TODO (first run): open the app's login screen and replace each selector with
 * the highest-priority unique match available (testid > aria-label > role > id
 * > semantic css). Record the change in `.claude/memories/selector-history.md`.
 */
export const loginSelectors = {
  emailInput: 'input[name="email"]',
  passwordInput: 'input[name="password"]',
  signInButton: 'button[type="submit"]',
  forgotPasswordLink: 'a[href*="forgot"]',
  /**
   * Inline error surfaced on bad credentials. Matched by text so it survives
   * the several render paths a form error can take (server auth error vs
   * per-field validation). Broaden the alternation rather than adding a
   * positional selector when a new error surface appears.
   */
  errorMessage:
    "p:text-matches('invalid email or password|rate limit|incorrect|unauthorized|invalid credentials|account.*lock|too many', 'i')",
} as const;
