import { type Page, type Locator, expect } from "@playwright/test";
import { loginSelectors } from "../../locators/login/login.locator.js";
import { env } from "../../shared/env.js";

/**
 * Page Object for the {{APP_NAME}} login screen.
 *
 * SEED FILE: generated by `/qa-agent:setup` — it is also the reference pattern
 * every generated POM follows (CLAUDE.md §6):
 *  - constructor takes `page`, exposes locators as readonly fields built from
 *    `locators/<module>/<module>.locator.ts` (the only place a raw selector
 *    may live)
 *  - actions are verbs (`enterUsername`), return `Promise<void>`
 *  - no business assertions inside actions — those belong in the spec or step
 *  - never call `page.waitForTimeout` — rely on Playwright auto-waiting
 */
export class LoginPage {
  readonly emailInput: Locator;
  readonly passwordInput: Locator;
  readonly signInButton: Locator;
  readonly forgotPasswordLink: Locator;
  readonly errorMessage: Locator;

  constructor(private readonly page: Page) {
    this.emailInput = page.locator(loginSelectors.emailInput);
    this.passwordInput = page.locator(loginSelectors.passwordInput);
    this.signInButton = page.locator(loginSelectors.signInButton);
    this.forgotPasswordLink = page.locator(loginSelectors.forgotPasswordLink);
    this.errorMessage = page.locator(loginSelectors.errorMessage);
  }

  /**
   * Opens the login screen and waits for it to be interactive.
   *
   * Staging auth bundles load slowly and unstably, so a bare `goto` plus the
   * default 5s visibility timeout races the paint and the email field
   * intermittently "doesn't exist". The hardening below is deliberate:
   *  - settle the navigation (`domcontentloaded`, then best-effort `networkidle`)
   *  - assert the email field with an explicit generous timeout
   *  - one bounded retry to absorb a transient bad load
   * No `page.waitForTimeout` (banned) and no unbounded loop.
   */
  async navigate(): Promise<void> {
    const url = env.ssoLoginUrl || "/login";

    const open = async (): Promise<void> => {
      await this.page.goto(url, { waitUntil: "domcontentloaded" });
      await this.page
        .waitForLoadState("networkidle", { timeout: 15_000 })
        .catch(() => undefined);
    };

    await open();
    try {
      await expect(this.emailInput).toBeVisible({ timeout: 30_000 });
    } catch {
      await open();
      await expect(this.emailInput).toBeVisible({ timeout: 30_000 });
    }
  }

  async enterUsername(username: string): Promise<void> {
    await this.emailInput.fill(username);
  }

  async enterPassword(password: string): Promise<void> {
    await this.passwordInput.fill(password);
  }

  async clickSignIn(): Promise<void> {
    await this.signInButton.click();
  }

  /**
   * Full happy-path login. Resolves once the post-login URL is reached
   * (`POST_LOGIN_URL_PATTERN` in `.env`). One bounded retry rides out a
   * transient bad submit — no hard wait, no unbounded loop.
   */
  async login(username = env.userId, password = env.userPwd): Promise<void> {
    const landed = new RegExp(env.postLoginUrlPattern);

    const submit = async (): Promise<void> => {
      await this.navigate();
      await this.enterUsername(username);
      await this.enterPassword(password);
      await this.clickSignIn();
      await this.page.waitForURL(landed, { timeout: 30_000 });
    };

    try {
      await submit();
    } catch {
      await submit();
    }
  }

  async expectLoginError(): Promise<void> {
    await expect(this.errorMessage.first()).toBeVisible();
  }
}
